# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/Desktop/Progetti/VisualSuffixTree

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/Desktop/Progetti/VisualSuffixTree

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/Desktop/Progetti/VisualSuffixTree/CMakeFiles /root/Desktop/Progetti/VisualSuffixTree/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/Desktop/Progetti/VisualSuffixTree/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named VisualSuffixTree

# Build rule for target.
VisualSuffixTree: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 VisualSuffixTree
.PHONY : VisualSuffixTree

# fast build rule for target.
VisualSuffixTree/fast:
	$(MAKE) -f CMakeFiles/VisualSuffixTree.dir/build.make CMakeFiles/VisualSuffixTree.dir/build
.PHONY : VisualSuffixTree/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/VisualSuffixTree.dir/build.make CMakeFiles/VisualSuffixTree.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/VisualSuffixTree.dir/build.make CMakeFiles/VisualSuffixTree.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/VisualSuffixTree.dir/build.make CMakeFiles/VisualSuffixTree.dir/main.cpp.s
.PHONY : main.cpp.s

src/ConfigParser.o: src/ConfigParser.cpp.o

.PHONY : src/ConfigParser.o

# target to build an object file
src/ConfigParser.cpp.o:
	$(MAKE) -f CMakeFiles/VisualSuffixTree.dir/build.make CMakeFiles/VisualSuffixTree.dir/src/ConfigParser.cpp.o
.PHONY : src/ConfigParser.cpp.o

src/ConfigParser.i: src/ConfigParser.cpp.i

.PHONY : src/ConfigParser.i

# target to preprocess a source file
src/ConfigParser.cpp.i:
	$(MAKE) -f CMakeFiles/VisualSuffixTree.dir/build.make CMakeFiles/VisualSuffixTree.dir/src/ConfigParser.cpp.i
.PHONY : src/ConfigParser.cpp.i

src/ConfigParser.s: src/ConfigParser.cpp.s

.PHONY : src/ConfigParser.s

# target to generate assembly for a file
src/ConfigParser.cpp.s:
	$(MAKE) -f CMakeFiles/VisualSuffixTree.dir/build.make CMakeFiles/VisualSuffixTree.dir/src/ConfigParser.cpp.s
.PHONY : src/ConfigParser.cpp.s

src/Header.o: src/Header.cpp.o

.PHONY : src/Header.o

# target to build an object file
src/Header.cpp.o:
	$(MAKE) -f CMakeFiles/VisualSuffixTree.dir/build.make CMakeFiles/VisualSuffixTree.dir/src/Header.cpp.o
.PHONY : src/Header.cpp.o

src/Header.i: src/Header.cpp.i

.PHONY : src/Header.i

# target to preprocess a source file
src/Header.cpp.i:
	$(MAKE) -f CMakeFiles/VisualSuffixTree.dir/build.make CMakeFiles/VisualSuffixTree.dir/src/Header.cpp.i
.PHONY : src/Header.cpp.i

src/Header.s: src/Header.cpp.s

.PHONY : src/Header.s

# target to generate assembly for a file
src/Header.cpp.s:
	$(MAKE) -f CMakeFiles/VisualSuffixTree.dir/build.make CMakeFiles/VisualSuffixTree.dir/src/Header.cpp.s
.PHONY : src/Header.cpp.s

src/NodeInfo.o: src/NodeInfo.cpp.o

.PHONY : src/NodeInfo.o

# target to build an object file
src/NodeInfo.cpp.o:
	$(MAKE) -f CMakeFiles/VisualSuffixTree.dir/build.make CMakeFiles/VisualSuffixTree.dir/src/NodeInfo.cpp.o
.PHONY : src/NodeInfo.cpp.o

src/NodeInfo.i: src/NodeInfo.cpp.i

.PHONY : src/NodeInfo.i

# target to preprocess a source file
src/NodeInfo.cpp.i:
	$(MAKE) -f CMakeFiles/VisualSuffixTree.dir/build.make CMakeFiles/VisualSuffixTree.dir/src/NodeInfo.cpp.i
.PHONY : src/NodeInfo.cpp.i

src/NodeInfo.s: src/NodeInfo.cpp.s

.PHONY : src/NodeInfo.s

# target to generate assembly for a file
src/NodeInfo.cpp.s:
	$(MAKE) -f CMakeFiles/VisualSuffixTree.dir/build.make CMakeFiles/VisualSuffixTree.dir/src/NodeInfo.cpp.s
.PHONY : src/NodeInfo.cpp.s

src/NodeInfoStructure.o: src/NodeInfoStructure.cpp.o

.PHONY : src/NodeInfoStructure.o

# target to build an object file
src/NodeInfoStructure.cpp.o:
	$(MAKE) -f CMakeFiles/VisualSuffixTree.dir/build.make CMakeFiles/VisualSuffixTree.dir/src/NodeInfoStructure.cpp.o
.PHONY : src/NodeInfoStructure.cpp.o

src/NodeInfoStructure.i: src/NodeInfoStructure.cpp.i

.PHONY : src/NodeInfoStructure.i

# target to preprocess a source file
src/NodeInfoStructure.cpp.i:
	$(MAKE) -f CMakeFiles/VisualSuffixTree.dir/build.make CMakeFiles/VisualSuffixTree.dir/src/NodeInfoStructure.cpp.i
.PHONY : src/NodeInfoStructure.cpp.i

src/NodeInfoStructure.s: src/NodeInfoStructure.cpp.s

.PHONY : src/NodeInfoStructure.s

# target to generate assembly for a file
src/NodeInfoStructure.cpp.s:
	$(MAKE) -f CMakeFiles/VisualSuffixTree.dir/build.make CMakeFiles/VisualSuffixTree.dir/src/NodeInfoStructure.cpp.s
.PHONY : src/NodeInfoStructure.cpp.s

src/ObjNode.o: src/ObjNode.cpp.o

.PHONY : src/ObjNode.o

# target to build an object file
src/ObjNode.cpp.o:
	$(MAKE) -f CMakeFiles/VisualSuffixTree.dir/build.make CMakeFiles/VisualSuffixTree.dir/src/ObjNode.cpp.o
.PHONY : src/ObjNode.cpp.o

src/ObjNode.i: src/ObjNode.cpp.i

.PHONY : src/ObjNode.i

# target to preprocess a source file
src/ObjNode.cpp.i:
	$(MAKE) -f CMakeFiles/VisualSuffixTree.dir/build.make CMakeFiles/VisualSuffixTree.dir/src/ObjNode.cpp.i
.PHONY : src/ObjNode.cpp.i

src/ObjNode.s: src/ObjNode.cpp.s

.PHONY : src/ObjNode.s

# target to generate assembly for a file
src/ObjNode.cpp.s:
	$(MAKE) -f CMakeFiles/VisualSuffixTree.dir/build.make CMakeFiles/VisualSuffixTree.dir/src/ObjNode.cpp.s
.PHONY : src/ObjNode.cpp.s

src/SvgCreator.o: src/SvgCreator.cpp.o

.PHONY : src/SvgCreator.o

# target to build an object file
src/SvgCreator.cpp.o:
	$(MAKE) -f CMakeFiles/VisualSuffixTree.dir/build.make CMakeFiles/VisualSuffixTree.dir/src/SvgCreator.cpp.o
.PHONY : src/SvgCreator.cpp.o

src/SvgCreator.i: src/SvgCreator.cpp.i

.PHONY : src/SvgCreator.i

# target to preprocess a source file
src/SvgCreator.cpp.i:
	$(MAKE) -f CMakeFiles/VisualSuffixTree.dir/build.make CMakeFiles/VisualSuffixTree.dir/src/SvgCreator.cpp.i
.PHONY : src/SvgCreator.cpp.i

src/SvgCreator.s: src/SvgCreator.cpp.s

.PHONY : src/SvgCreator.s

# target to generate assembly for a file
src/SvgCreator.cpp.s:
	$(MAKE) -f CMakeFiles/VisualSuffixTree.dir/build.make CMakeFiles/VisualSuffixTree.dir/src/SvgCreator.cpp.s
.PHONY : src/SvgCreator.cpp.s

src/SvgObject/StatusBar.o: src/SvgObject/StatusBar.cpp.o

.PHONY : src/SvgObject/StatusBar.o

# target to build an object file
src/SvgObject/StatusBar.cpp.o:
	$(MAKE) -f CMakeFiles/VisualSuffixTree.dir/build.make CMakeFiles/VisualSuffixTree.dir/src/SvgObject/StatusBar.cpp.o
.PHONY : src/SvgObject/StatusBar.cpp.o

src/SvgObject/StatusBar.i: src/SvgObject/StatusBar.cpp.i

.PHONY : src/SvgObject/StatusBar.i

# target to preprocess a source file
src/SvgObject/StatusBar.cpp.i:
	$(MAKE) -f CMakeFiles/VisualSuffixTree.dir/build.make CMakeFiles/VisualSuffixTree.dir/src/SvgObject/StatusBar.cpp.i
.PHONY : src/SvgObject/StatusBar.cpp.i

src/SvgObject/StatusBar.s: src/SvgObject/StatusBar.cpp.s

.PHONY : src/SvgObject/StatusBar.s

# target to generate assembly for a file
src/SvgObject/StatusBar.cpp.s:
	$(MAKE) -f CMakeFiles/VisualSuffixTree.dir/build.make CMakeFiles/VisualSuffixTree.dir/src/SvgObject/StatusBar.cpp.s
.PHONY : src/SvgObject/StatusBar.cpp.s

src/TreeParser.o: src/TreeParser.cpp.o

.PHONY : src/TreeParser.o

# target to build an object file
src/TreeParser.cpp.o:
	$(MAKE) -f CMakeFiles/VisualSuffixTree.dir/build.make CMakeFiles/VisualSuffixTree.dir/src/TreeParser.cpp.o
.PHONY : src/TreeParser.cpp.o

src/TreeParser.i: src/TreeParser.cpp.i

.PHONY : src/TreeParser.i

# target to preprocess a source file
src/TreeParser.cpp.i:
	$(MAKE) -f CMakeFiles/VisualSuffixTree.dir/build.make CMakeFiles/VisualSuffixTree.dir/src/TreeParser.cpp.i
.PHONY : src/TreeParser.cpp.i

src/TreeParser.s: src/TreeParser.cpp.s

.PHONY : src/TreeParser.s

# target to generate assembly for a file
src/TreeParser.cpp.s:
	$(MAKE) -f CMakeFiles/VisualSuffixTree.dir/build.make CMakeFiles/VisualSuffixTree.dir/src/TreeParser.cpp.s
.PHONY : src/TreeParser.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... VisualSuffixTree"
	@echo "... edit_cache"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/ConfigParser.o"
	@echo "... src/ConfigParser.i"
	@echo "... src/ConfigParser.s"
	@echo "... src/Header.o"
	@echo "... src/Header.i"
	@echo "... src/Header.s"
	@echo "... src/NodeInfo.o"
	@echo "... src/NodeInfo.i"
	@echo "... src/NodeInfo.s"
	@echo "... src/NodeInfoStructure.o"
	@echo "... src/NodeInfoStructure.i"
	@echo "... src/NodeInfoStructure.s"
	@echo "... src/ObjNode.o"
	@echo "... src/ObjNode.i"
	@echo "... src/ObjNode.s"
	@echo "... src/SvgCreator.o"
	@echo "... src/SvgCreator.i"
	@echo "... src/SvgCreator.s"
	@echo "... src/SvgObject/StatusBar.o"
	@echo "... src/SvgObject/StatusBar.i"
	@echo "... src/SvgObject/StatusBar.s"
	@echo "... src/TreeParser.o"
	@echo "... src/TreeParser.i"
	@echo "... src/TreeParser.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

